%YAML:1.0
---
aruco-dictionary: TAG16h5
aruco-detectMode: DM_VIDEO_FAST
aruco-cornerRefinementM: CORNER_LINES
aruco-thresMethod: THRES_AUTO_FIXED
aruco-maxThreads: 1
aruco-borderDistThres: 1.4999999664723873e-02
aruco-lowResMarkerSize: 20
aruco-minSize: 0.
aruco-minSize_pix: -1
aruco-enclosedMarker: 0
aruco-NAttemptsAutoThresFix: 3
aruco-AdaptiveThresWindowSize: -1
aruco-ThresHold: 79
aruco-AdaptiveThresWindowSize_range: 0
aruco-markerWarpPixSize: 5
aruco-autoSize: 1
aruco-ts: 3.0000001192092896e-01
aruco-pyrfactor: 2.
aruco-error_correction_rate: 0.
